//<![CDATA[
//Pre Auto Selection
$('i[rel="pre"]').replaceWith(function(){return $("<pre><code>"+$(this).html()+"</code></pre>")});for(var pres=document.querySelectorAll("pre,kbd,blockquote,i"),i=0;i<pres.length;i++)pres[i].addEventListener("dblclick",function(){var e=getSelection(),t=document.createRange();t.selectNodeContents(this),e.removeAllRanges(),e.addRange(t)},!1);
// Pesan Komentar
$(document).ready(function(){$(".parser").click(function(){$("#parser").slideToggle("fast")})});
function convert(){var ele1 = document.getElementById("somewhere");var replaced;replaced = ele1.value;replaced = replaced.replace(/&/ig, "&amp;");replaced = replaced.replace(/</ig, "&lt;");replaced = replaced.replace(/>/ig, "&gt;");replaced = replaced.replace(/"/ig, "&quot;");replaced = replaced.replace(/&#177;/ig, "&plusmn;");replaced = replaced.replace(/&#169;/ig, "&copy;");replaced = replaced.replace(/&#174;/ig, "&reg;");replaced = replaced.replace(/ya'll/ig, "ya'll");ele1.value = replaced;};
// Sticky
$(function(){if($("#Label1").length){var o=$("#Label1"),t=$("#Label1").offset().top,i=$("#Label1").height();$(window).scroll(function(){var s=$("#footer-wrapper").offset().top-i-70,f=$(window).scrollTop();if(f>t?o.css({position:"fixed",top:70}):o.css("position","static"),f>s){var n=s-f;o.css({top:n})}})}});
// Disqus
var disqus_shortname="bloggerekibi";var disqus_url = disqus_blogger_current_url;(function () {"use strict";var get_comment_block = function () {var block = document.getElementById('comments');
if (!block) {block = document.getElementById('disqus-blogger-comment-block');}return block;};var comment_block = get_comment_block();if (!!comment_block) {var disqus_div = document.createElement('div');disqus_div.id = 'disqus_thread';comment_block.innerHTML = '';comment_block.appendChild(disqus_div);comment_block.style.display = 'block';var dsq = document.createElement('script');dsq.async = true;dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';(document.getElementsByTagName('head')[0] || document.body).appendChild(dsq);}})();!function(e,n,t){var o,c=e.getElementsByTagName(n)[0];e.getElementById(t)||(o=e.createElement(n),o.id=t,o.src="//connect.facebook.net/tr_TR/sdk.js#xfbml=1&version=v2.3",c.parentNode.insertBefore(o,c))}(document,"script","facebook-jssdk");var divs = ["disqus-box", "blogger-box", "facebook-box"];var visibleDivId = null;function toggleVisibility(divId) {if(visibleDivId === divId) {visibleDivId = null;} else {visibleDivId = divId;}hideNonVisibleDivs();}function hideNonVisibleDivs() {var i, divId, div;for(i = 0; i < divs.length; i++) {divId = divs[i];div = document.getElementById(divId);if(visibleDivId === divId) {div.style.display = "block";} else {div.style.display = "none";}}}$(".commentbtn").click(function (e) {$(this).addClass("btncurrent").siblings().removeClass("btncurrent");});
//]]>